### ISSUE TITLE
nextjs 13

### ISSUE THREAD

**Issue by meirpertzz** [nhost/quickstart-nextjs#4]
Hi, are you planning on creating some beta starter-template for nextJS 13?
If not, I would like some instructions.

Thank you very much.
love and appreciate your work.

**Comment by Zaid-maker** [comment]
> Hi, are you planning on creating some beta starter-template for nextJS 13? If not, I would like some instructions.
> 
> Thank you very much. love and appreciate your work.

#6 here u you go fam
